# Generated by Django 2.1.4 on 2019-01-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0005_auto_20190117_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, null=True, unique=True)),
                ('command', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='automation',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Configure.Command'),
        ),
    ]
