# Generated by Django 2.1.4 on 2019-01-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automation',
            old_name='Address',
            new_name='device',
        ),
    ]
