# Generated by Django 2.1.4 on 2019-01-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_auto_20190117_0958'),
        ('Configure', '0002_auto_20190118_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.Device')),
            ],
        ),
        migrations.RemoveField(
            model_name='automation',
            name='device',
        ),
        migrations.AddField(
            model_name='automation',
            name='device',
            field=models.ManyToManyField(to='Inventory.Device'),
        ),
    ]
