# Generated by Django 2.1.4 on 2019-01-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configure', '0004_auto_20190118_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceconf',
            name='hostname',
        ),
        migrations.RenameField(
            model_name='automation',
            old_name='command',
            new_name='command1',
        ),
        migrations.DeleteModel(
            name='DeviceConf',
        ),
    ]
