# Generated by Django 2.1.4 on 2019-01-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configure', '0005_auto_20190118_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automation',
            old_name='command1',
            new_name='command',
        ),
    ]
