# Generated by Django 2.1.4 on 2019-01-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configure', '0012_auto_20190119_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='device',
            field=models.ManyToManyField(related_name='self', to='Inventory.Device'),
        ),
    ]
