# Generated by Django 2.1.4 on 2019-01-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='perangkat',
            new_name='Device',
        ),
    ]
