# Generated by Django 2.1.4 on 2019-01-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20190112_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='nama',
        ),
        migrations.AddField(
            model_name='device',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='hostname',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
