# Generated by Django 2.1.4 on 2019-01-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20190116_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
